Implement function / function expression config
yeet-bix/create-react-component-vscode pull request #6
Opened 2019-11-30 23:11 UTC by eddeee888

This PR adds a new config option that allows people to choose whether they want the component be written as function or function expression.

- Add config option to generate either function or function expression.
- Use added option to generate the JS/TS templates

TODO: 
[ ] Test - how does it work? Pls halp 💀

2019-12-01 07:30 UTC, yeet-bix requested changes
Just need to rebase but looks good! 👍 

FYI:
* `npm run test:unit`
* `npm run test:integration`

Don't worry about tests. 
The current test suite uses [sinon](https://sinonjs.org/) to mock the vscode window. I have created an issue here to refactor the tests: #7 and will add test coverage for this as part of the refactor 😄

2019-12-01 07:30 UTC, yeet-bix commented on src/extension.ts
> +                functionType: <FunctionType>config.get('functionType')
Some changes came in just before you created this PR. I have changed the type casts here to use the `as` syntax. You'll have to rebase 😬

2019-12-01 07:30 UTC, yeet-bix commented on src/template/javascriptTemplate.ts
> +${functionType === FunctionType.Expression && `const ${name}: React.FunctionComponent<Props> = ({ }) => {`}
Accidentally have types here in the javascript template

```suggestion
${functionType === FunctionType.Expression && `const ${name} = ({ }) => {`}
```

2019-12-01 07:35 UTC, yeet-bix commented
Could you awesome add some docs for the setting in the README as well? 📝

2019-12-02 10:50 UTC, eddeee888 commented
I can't seem to run integration test in my machine.. The test window keeps crashing. Please test this before merging 😬

2019-12-03 10:37 UTC, yeet-bix commented
The current version outputs:
```typescript
import React from 'react';

export interface MyComponentProps {}

function MyComponent({ }: MyComponentProps) {
false
    return <>MyComponent</>
};

export default MyComponent;
```

I think we will need something more explicit like a ternary:
```typescript
${functionType === FunctionType.Function ? `function ${name}({}) {` : ``}
${functionType === FunctionType.Expression ? `const ${name} = ({}) => {` : ``}
```


To manually test, you can either:

1. Press F5 and run the extension in a debug window
2. Run `vsce package` which will package the extension locally. You can then install the extension locally.

2019-12-03 10:56 UTC, eddeee888 commented
Thanks! I used "Extension Tests" instead of "Run extension" in debug mode which caused the test editor to open then close straight away 🤦‍♂ 

I have updated the code as well

2019-12-03 22:14 UTC, yeet-bix approved these changes
:shipit:

2019-12-03 22:14 UTC, merged